weather:
  pull:
    cron: 0 0 * * * ?
  round:
    to-unit: HOURS
  store:
    expire:
      in: 72
      time-unit: HOURS
  open-weather:
    host: api.openweathermap.org
    port: 443
    ssl: true
    api/mp-rest/url: https://api.openweathermap.org/data
    api/mp-rest/scope: javax.inject.Singleton

quarkus:
  application:
    name: airq-weather-cache
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://10.1.1.50:5432/warehouse
    reactive:
      url: postgresql://10.1.1.50:5432/warehouse
  http:
    cors: true
  vertx:
    prefer-native-transport: true

"%dev":
  weather:
    pull:
      cron: 0 * * * * ?
    round:
      to-unit: HOURS
    store:
      expire:
        in: 72
        time-unit: HOURS
  quarkus:
    redis:
      hosts: redis://localhost:6379
